### ISSUE TITLE
Issues cordova plugin 3.6.1 android logcat

### ISSUE THREAD

**Issue by simone-compagnone** [ibm-mobile-push/cordova#7]
Hi,
we are trying to update the ibm plugin 3.5.0 to 3.6.1 in our new platform android.
Our Cordova platform Configuration has following versions: 
- Cordova 6.5.0 
- Android cordova platform 6.4.0 

After send the push notification with Watson Campaign we can't receive the push notification. On the logcat of device (Samsung s8 with android 8.0):

E/IBM.MCE 3.7.1.2.3 : WakefulIntentService: Failed to generate listener com.ibm.mce.sdk.events.EventsAlarmListener
java.lang.IllegalArgumentException: No such service ComponentInfo{it.nogood.container/com.ibm.mce.sdk.job.MceJobService}
at android.os.Parcel.readException(Parcel.java:1962)
at android.os.Parcel.readException(Parcel.java:1904)
at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:180)
at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
at com.ibm.mce.sdk.job.MceJobService.scheduleForNow(Unknown Source:56)
at com.ibm.mce.sdk.wi.WakefulIntentService.sendWakefulWork(Unknown Source:125)
at com.ibm.mce.sdk.wi.WakefulIntentService.sendWakefulWork(Unknown Source:48)
at com.ibm.mce.sdk.wi.WakefulAlarmListener.onTrigger(Unknown Source:4)
at com.ibm.mce.sdk.wi.BaseAlarmReceiver.onReceive(Unknown Source:247)
at com.ibm.mce.sdk.wi.AlarmReceiver.onReceive(Unknown Source:3)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3390)
at android.app.ActivityThread.-wrap18(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6938)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**********************************

IBM.MCE 3.7.1.2.3 : WakefulIntentService: Failed to generate listener com.ibm.mce.sdk.events.EventsAlarmListener
java.lang.IllegalArgumentException: No such service ComponentInfo{it.nogood.container/com.ibm.mce.sdk.job.MceJobService}
at android.os.Parcel.readException(Parcel.java:1962)
at android.os.Parcel.readException(Parcel.java:1904)
at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:180)
at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
at com.ibm.mce.sdk.job.MceJobService.scheduleForNow(Unknown Source:56)
at com.ibm.mce.sdk.wi.WakefulIntentService.sendWakefulWork(Unknown Source:125)
at com.ibm.mce.sdk.wi.WakefulIntentService.sendWakefulWork(Unknown Source:48)
at com.ibm.mce.sdk.wi.WakefulAlarmListener.onTrigger(Unknown Source:4)
at com.ibm.mce.sdk.wi.BaseAlarmReceiver.onReceive(Unknown Source:247)
at com.ibm.mce.sdk.wi.AlarmReceiver.onReceive(Unknown Source:3)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3390)
at android.app.ActivityThread.-wrap18(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6938)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by mvergarair** [comment]
Good luck trying to get a response from IBM 👎
